pub mod display;
pub mod primitive_data;
pub mod custom_type;
pub mod enum_type;
pub mod conversion;
pub mod conditional_branch;
pub mod function;
pub mod generics_function;
pub mod generics_method;
pub mod generics_trait;
pub mod generics_bound;
pub mod generics_multi_bound;
pub mod generics_associated_type;
pub mod trait_intro;
pub mod trait_dyn;
// pub mod trait_overload_operator;
pub mod trait_iterator;
pub mod trait_supertraits;
pub mod macro_rules_all;
pub mod error_handling_result;
pub mod error_handling_result_map;
pub mod error_handling_early_return;
// pub mod error_handling_multi_define;
