[package]
name = "json-typegen-01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
json_typegen = "0.7.0"
json_typegen_shared = "0.7.0"
serde = "1.0.190"
serde_derive = "1.0.190"
